apiVersion: v1
clusters:
  - cluster:
      certificate-authority: /home/aelean/.minikube/ca.crt
      server: https://192.168.49.2:8443
    name: minikube
contexts:
  - context:
      cluster: minikube
      namespace: homework
      user: cd
    name: admin-context
current-context: admin-context
kind: Config
preferences: {}
users:
  - name: cd
    user:
      tokenFile: token
