apiVersion: v1
kind: ConfigMap
metadata:
  name: homework-config
  namespace: homework
data:
  homework.info: |
    homework.num=4
    homework.label=kubernetes-volumes
    homework.author=DmitryDavydkin
