apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume
  namespace: homework
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/pv0001/"
